### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by controlthedemon** [m4eba/eurosportplayer-downloader#3]
Getting this error:

TimeoutError: Timeout exceeded while waiting for event
    at Timeout.<anonymous> (d:\eurosportplayer-downloader-master\node_modules\pu
ppeteer\lib\helper.js:200:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
  -- ASYNC --
    at Page.<anonymous> (d:\eurosportplayer-downloader-master\node_modules\puppe
teer\lib\helper.js:111:15)
    at video (d:\eurosportplayer-downloader-master\download.js:211:27)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)
    at async d:\eurosportplayer-downloader-master\download.js:242:18 {
  name: 'TimeoutError'
}
TypeError: Cannot read property 'm3u8' of null
    at d:\eurosportplayer-downloader-master\download.js:249:18

**Comment by m4eba** [comment]
It's a problem with the eurosport backend, you get that also occasionally in the browser. Maybe i could increase the tries and make a better error message.
